### ISSUE TITLE
ImageApi has no example response

### ISSUE THREAD

**Issue by Benehiko** [ReolinkCameraAPI/reolink-python-api#33]
The ImageApi has no example response.

https://github.com/ReolinkCameraAPI/reolink-python-api/blob/master/api/image.py

#27

**Comment by Lanwalker** [comment]
Reolink support told me to use this CAMERA FIRMWARE UPDATE on an E1 Pro that had network issues ( on December 9, 2020 )... not sure if this will help anybody.
https://support.reolink.com/hc/en-us/articles/900004231023-11-02-2020-Firmware-for-E1-Pro-513SD5-

BTW, Reolink's new client takes out some decent features the previous version had( has ) and moves some of the information from the system area to the camera area for those trying to find the firmware information, etc.. Reolink needs to update their upgrade procedures for the new clients. ( luckily I had 2 machines ... one with the new client and one with the old client so I could compare to check the camera firmware to upgrade it )
I just passed that information to Reolink support a little while ago. I have 5 Reolink cameras now.. an Argus PT and Argus Pro for outside and 3 of the E1 Pro for inside... 2 newer versions and an older version I just upgraded the firmware in since it lost network connectivity and had to be returned to factory settings and re-installed and then upgraded the firmware.

Robert Gamble
Rfgamble@yahoo.com (preferred )

On Wednesday, December 9, 2020, 12:24:06 PM EST, Alano Terblanche <notifications@github.com> wrote: 







The ImageApi has no example response.

https://github.com/ReolinkCameraAPI/reolink-python-api/blob/master/api/image.py

#27

**Comment by themoosman** [comment]
@Lanwalker Did you post your comment on the correct issue?  I'm not quite sure what that comment has to do with this issue.

**Comment by Lanwalker** [comment]
> 
> 
> @Lanwalker Did you post your comment on the correct issue? I'm not quite sure what that comment has to do with this issue.

Sorry. Just letting people working in the camera environment know a firmware update for the Reolink cameras was out there... many different directions going thru here. I'm done dealing with communist chinese Reolink crap anymore... their support and warranty is useless. Buy American Made. 2nd E1 Pro with issues and now they want to refund my money AFTER I PAY TO SEND IT BACK. I'll keep it so I can tear it apart first. $16 to send it back with tracking( think I would get the $44 + the $16  ? ). Again, Sorry if this went to the wrong area... I have been watching quite a few camera areas lately.
